export interface LinuxDistro {
  id: string;
  name: string;
  tagline: string;
  description: string;
  logo: string;
  badge?: string;
  base: "Debian" | "Ubuntu" | "Arch" | "Red Hat / Fedora" | "Independent" | "openSUSE";
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  releaseModel: "Regular / LTS" | "Rolling" | "Semi-Rolling" | "Immutable";
  defaultDesktop: string;
  supportedDesktops: string[];
  packageManager: string;
  packageManagerCmd: string;
  targetAudience: string[];
  runsOnOldHardware: boolean;
  minRamGb: number;
  recommendedRamGb: number;
  gamingScore: number; // 1 to 10
  developerScore: number; // 1 to 10
  serverScore: number; // 1 to 10
  pros: string[];
  cons: string[];
  websiteUrl: string;
  downloadUrl: string;
  originCountry: string;
  firstReleaseYear: number;
}

export const DISTROS_DATA: LinuxDistro[] = [
  {
    id: "ubuntu",
    name: "Ubuntu",
    tagline: "The world's most popular Linux desktop and server OS",
    description:
      "Ubuntu is an open-source Debian-based Linux distribution developed by Canonical. It is renowned for its ease of use, extensive hardware compatibility, massive community, and 5-year Long Term Support (LTS) releases.",
    logo: "🟠",
    badge: "Most Popular",
    base: "Debian",
    difficulty: "Beginner",
    releaseModel: "Regular / LTS",
    defaultDesktop: "GNOME",
    supportedDesktops: ["GNOME", "KDE Plasma (Kubuntu)", "XFCE (Xubuntu)", "MATE", "Budgie"],
    packageManager: "APT / Snap",
    packageManagerCmd: "sudo apt update && sudo apt install <pkg>",
    targetAudience: ["Beginners", "Developers", "Servers", "Enterprises"],
    runsOnOldHardware: false,
    minRamGb: 4,
    recommendedRamGb: 8,
    gamingScore: 8,
    developerScore: 9,
    serverScore: 10,
    pros: [
      "Vast community and documentation",
      "Out-of-the-box hardware drivers",
      "Enterprise-grade stability & 5-year LTS",
      "Huge software availability via APT & Snap",
    ],
    cons: [
      "Snap packages can be slower to launch",
      "Telemetry enabled by default (opt-out)",
      "GNOME customization can feel heavy on older hardware",
    ],
    websiteUrl: "https://ubuntu.com",
    downloadUrl: "https://ubuntu.com/download/desktop",
    originCountry: "Isle of Man / UK",
    firstReleaseYear: 2004,
  },
  {
    id: "linux-mint",
    name: "Linux Mint",
    tagline: "The ultimate classic desktop for Windows switchers",
    description:
      "Linux Mint is designed to work 'out of the box' with full multimedia support, an intuitive Windows-like Cinnamon desktop interface, and no forced snap packages.",
    logo: "🌿",
    badge: "Best for Beginners",
    base: "Ubuntu",
    difficulty: "Beginner",
    releaseModel: "Regular / LTS",
    defaultDesktop: "Cinnamon",
    supportedDesktops: ["Cinnamon", "MATE", "XFCE"],
    packageManager: "APT / Flatpak",
    packageManagerCmd: "sudo apt install <pkg>  or  flatpak install <pkg>",
    targetAudience: ["Windows Switchers", "Everyday Desktop", "Students"],
    runsOnOldHardware: true,
    minRamGb: 2,
    recommendedRamGb: 4,
    gamingScore: 8,
    developerScore: 8,
    serverScore: 5,
    pros: [
      "Familiar Windows-style taskbar and menu",
      "No snaps by default; native Flatpak support",
      "Extremely stable with Mint Software Manager",
      "Great driver manager for Nvidia and Wi-Fi",
    ],
    cons: [
      "Base is slightly older than bleeding-edge distros",
      "No official Wayland default yet in older versions",
      "Not built for high-end server deployments",
    ],
    websiteUrl: "https://linuxmint.com",
    downloadUrl: "https://linuxmint.com/download.php",
    originCountry: "Ireland",
    firstReleaseYear: 2006,
  },
  {
    id: "pop-os",
    name: "Pop!_OS",
    tagline: "Built for creators, makers, and gamers by System76",
    description:
      "Pop!_OS is an Ubuntu-based operating system designed for fast navigation, easy workspace organization, built-in window auto-tiling (COSMIC), and seamless hybrid graphics support.",
    logo: "🚀",
    badge: "Best for Gaming & STEM",
    base: "Ubuntu",
    difficulty: "Beginner",
    releaseModel: "Regular / LTS",
    defaultDesktop: "COSMIC (Rust)",
    supportedDesktops: ["COSMIC Desktop", "GNOME"],
    packageManager: "APT / Flatpak",
    packageManagerCmd: "sudo apt install <pkg>  or  flatpak install <pkg>",
    targetAudience: ["Gamers", "Developers", "AI & Data Scientists", "Creators"],
    runsOnOldHardware: false,
    minRamGb: 4,
    recommendedRamGb: 8,
    gamingScore: 10,
    developerScore: 10,
    serverScore: 6,
    pros: [
      "Dedicated ISO with pre-installed Nvidia drivers",
      "COSMIC Rust-based desktop with auto-tiling window manager",
      "Out-of-the-box support for CUDA, TensorFlow, and PyTorch",
      "Flatpak integration in Pop!_Shop",
    ],
    cons: ["Higher system requirements", "Release cadence tied to COSMIC desktop development"],
    websiteUrl: "https://pop.system76.com",
    downloadUrl: "https://pop.system76.com",
    originCountry: "USA",
    firstReleaseYear: 2017,
  },
  {
    id: "fedora",
    name: "Fedora Workstation",
    tagline: "Leading-edge Linux with pure GNOME and cutting-edge tech",
    description:
      "Fedora is a community-driven distro sponsored by Red Hat. It brings the latest Linux kernel, Wayland, PipeWire, and unmodified GNOME desktop with uncompromising open-source standards.",
    logo: "🔷",
    badge: "Developer Favorite",
    base: "Red Hat / Fedora",
    difficulty: "Intermediate",
    releaseModel: "Regular / LTS",
    defaultDesktop: "GNOME (Vanilla)",
    supportedDesktops: ["GNOME", "KDE Plasma", "XFCE", "Cinnamon", "i3", "Sway"],
    packageManager: "DNF / RPM / Flatpak",
    packageManagerCmd: "sudo dnf install <pkg>",
    targetAudience: ["Software Engineers", "DevOps", "Sysadmins", "Linux Enthusiasts"],
    runsOnOldHardware: false,
    minRamGb: 4,
    recommendedRamGb: 8,
    gamingScore: 8,
    developerScore: 10,
    serverScore: 9,
    pros: [
      "First to adopt modern Linux technologies (Wayland, PipeWire, Btrfs)",
      "Stock GNOME experience as intended by upstream",
      "Excellent container tools (Podman, Docker)",
      "Backed by Red Hat engineering",
    ],
    cons: [
      "6-month release cycle requires frequent upgrades",
      "Proprietary codecs must be enabled via RPM Fusion",
      "DNF can be slightly slower than Pacman",
    ],
    websiteUrl: "https://fedoraproject.org",
    downloadUrl: "https://fedoraproject.org/workstation/download",
    originCountry: "USA",
    firstReleaseYear: 2003,
  },
  {
    id: "arch-linux",
    name: "Arch Linux",
    tagline: "A lightweight, flexible, rolling-release distribution",
    description:
      "Arch Linux follows the KISS principle (Keep It Simple, Stupid). Users install the base system via command line and customize every piece from kernel to desktop, benefiting from the Arch User Repository (AUR).",
    logo: "🏹",
    badge: "For Advanced Users",
    base: "Arch",
    difficulty: "Advanced",
    releaseModel: "Rolling",
    defaultDesktop: "None (User Choice)",
    supportedDesktops: ["KDE Plasma", "GNOME", "Hyprland", "i3", "Sway", "XFCE"],
    packageManager: "Pacman / AUR",
    packageManagerCmd: "sudo pacman -S <pkg>  or  yay -S <pkg>",
    targetAudience: ["Power Users", "Linux Enthusiasts", "Customizers", "Tinkers"],
    runsOnOldHardware: true,
    minRamGb: 1,
    recommendedRamGb: 4,
    gamingScore: 9,
    developerScore: 10,
    serverScore: 6,
    pros: [
      "Arch User Repository (AUR) has virtually every piece of Linux software",
      "Bleeding edge rolling release: always latest kernel & drivers",
      "No bloat: install only what you need",
      "The Arch Wiki is the finest Linux documentation on Earth",
    ],
    cons: [
      "Manual CLI installation process",
      "Can occasionally require manual intervention on updates",
      "Steep learning curve for newcomers",
    ],
    websiteUrl: "https://archlinux.org",
    downloadUrl: "https://archlinux.org/download",
    originCountry: "Canada",
    firstReleaseYear: 2002,
  },
  {
    id: "debian",
    name: "Debian",
    tagline: "The Universal Operating System — bedrock of Linux",
    description:
      "Debian is one of the oldest and most respected Linux distributions. Known for extreme stability and strict free-software principles, it forms the foundation for Ubuntu, Mint, Kali, and hundreds more.",
    logo: "🌀",
    badge: "Rock Solid",
    base: "Debian",
    difficulty: "Intermediate",
    releaseModel: "Regular / LTS",
    defaultDesktop: "GNOME / XFCE",
    supportedDesktops: ["GNOME", "XFCE", "KDE Plasma", "MATE", "LXQt", "LXDE"],
    packageManager: "APT / dpkg",
    packageManagerCmd: "sudo apt update && sudo apt install <pkg>",
    targetAudience: ["Servers", "Production Infrastructure", "Stability Seekers"],
    runsOnOldHardware: true,
    minRamGb: 1,
    recommendedRamGb: 4,
    gamingScore: 6,
    developerScore: 8,
    serverScore: 10,
    pros: [
      "100% free and community governed",
      "Legendary rock-solid stability for mission critical systems",
      "Huge package repository with 60,000+ packages",
      "Extremely lightweight and versatile",
    ],
    cons: [
      "Software packages in Stable branch can be several versions behind",
      "Installer is less flashy than modern graphical installers",
    ],
    websiteUrl: "https://debian.org",
    downloadUrl: "https://debian.org/distrib",
    originCountry: "USA",
    firstReleaseYear: 1993,
  },
  {
    id: "manjaro",
    name: "Manjaro",
    tagline: "The power of Arch Linux made easy and user-friendly",
    description:
      "Manjaro provides the benefits of the Arch operating system combined with a focus on user-friendliness, automated hardware detection, and curated updates tested for 1-2 weeks before release.",
    logo: "🟩",
    badge: "Friendly Arch",
    base: "Arch",
    difficulty: "Intermediate",
    releaseModel: "Rolling",
    defaultDesktop: "KDE Plasma / XFCE / GNOME",
    supportedDesktops: ["KDE Plasma", "XFCE", "GNOME", "i3", "Cinnamon"],
    packageManager: "Pamac / Pacman / AUR",
    packageManagerCmd: "sudo pacman -S <pkg>  or  pamac install <pkg>",
    targetAudience: ["Gamers", "Intermediate Users", "Desktop Users"],
    runsOnOldHardware: true,
    minRamGb: 2,
    recommendedRamGb: 8,
    gamingScore: 9,
    developerScore: 9,
    serverScore: 5,
    pros: [
      "Graphical Pamac package manager with AUR, Flatpak, and Snap support",
      "Automatic hardware and GPU driver configuration",
      "Curated rolling release reduces sudden breakages",
      "Very active forum and community",
    ],
    cons: [
      "Delayed packages can occasionally create AUR compatibility desyncs",
      "Past SSL certificate renewal hiccups in community infrastructure",
    ],
    websiteUrl: "https://manjaro.org",
    downloadUrl: "https://manjaro.org/download",
    originCountry: "Germany / Austria",
    firstReleaseYear: 2011,
  },
  {
    id: "zorin-os",
    name: "Zorin OS",
    tagline: "Designed to make your computer faster, more powerful, and secure",
    description:
      "Zorin OS is specifically crafted as a drop-in replacement for Windows and macOS. It features the Zorin Appearance tool, letting you switch the entire desktop layout in one click.",
    logo: "🔷",
    badge: "Easiest Migration",
    base: "Ubuntu",
    difficulty: "Beginner",
    releaseModel: "Regular / LTS",
    defaultDesktop: "Zorin Desktop (GNOME customized)",
    supportedDesktops: ["Zorin Desktop", "XFCE (Zorin Lite)"],
    packageManager: "APT / Flatpak / Snap",
    packageManagerCmd: "sudo apt install <pkg>",
    targetAudience: ["Windows Switchers", "macOS Switchers", "Seniors", "Schools"],
    runsOnOldHardware: true,
    minRamGb: 2,
    recommendedRamGb: 4,
    gamingScore: 8,
    developerScore: 8,
    serverScore: 5,
    pros: [
      "One-click layout switch (Windows 11, Windows Classic, macOS, ChromeOS)",
      "Built-in Windows App Support (Wine & Bottles integration)",
      "Zorin Connect for syncing with Android phones",
      "Zorin Lite runs great on 15-year-old PCs",
    ],
    cons: [
      "Pro version with extra layouts is a paid tier",
      "Major updates released slightly later than standard Ubuntu",
    ],
    websiteUrl: "https://zorin.com/os",
    downloadUrl: "https://zorin.com/os/download",
    originCountry: "Ireland",
    firstReleaseYear: 2009,
  },
  {
    id: "opensuse",
    name: "openSUSE Tumbleweed & Leap",
    tagline: "The choice for sysadmins, developers, and desktop power users",
    description:
      "openSUSE offers two flavors: Tumbleweed (a rigorously automated QA-tested rolling release with openQA) and Leap (a rock-solid regular release aligned with SUSE Linux Enterprise). Features the famous YaST control center.",
    logo: "🦎",
    badge: "Enterprise Grade",
    base: "openSUSE",
    difficulty: "Intermediate",
    releaseModel: "Rolling",
    defaultDesktop: "KDE Plasma / GNOME",
    supportedDesktops: ["KDE Plasma", "GNOME", "XFCE", "i3"],
    packageManager: "Zypper / RPM / Flatpak",
    packageManagerCmd: "sudo zypper install <pkg>",
    targetAudience: ["Developers", "Sysadmins", "Power Users", "Enterprises"],
    runsOnOldHardware: false,
    minRamGb: 4,
    recommendedRamGb: 8,
    gamingScore: 8,
    developerScore: 9,
    serverScore: 10,
    pros: [
      "YaST: The most powerful graphical system configuration center in Linux",
      "Automated openQA testing prevents broken rolling releases",
      "Snapper Btrfs snapshot rollbacks out of the box",
      "First-class KDE Plasma integration",
    ],
    cons: [
      "Smaller third-party community compared to Ubuntu/Debian",
      "Zypper is slightly slower than pacman",
    ],
    websiteUrl: "https://opensuse.org",
    downloadUrl: "https://get.opensuse.org",
    originCountry: "Germany",
    firstReleaseYear: 2005,
  },
  {
    id: "endeavouros",
    name: "EndeavourOS",
    tagline: "A terminal-centric Linux distro with a vibrant community",
    description:
      "EndeavourOS is an Arch-based distro that provides an easy Calamares installer, a minimal clean desktop, and a welcoming community for users who want pure Arch without the manual install overhead.",
    logo: "🚀",
    badge: "Pure Arch Experience",
    base: "Arch",
    difficulty: "Intermediate",
    releaseModel: "Rolling",
    defaultDesktop: "XFCE (Offline) / Choice online",
    supportedDesktops: ["KDE Plasma", "GNOME", "XFCE", "Hyprland", "i3", "Sway", "Cinnamon"],
    packageManager: "Pacman / Yay",
    packageManagerCmd: "yay -S <pkg>  or  sudo pacman -S <pkg>",
    targetAudience: ["Intermediate Users", "Developers", "Gamers", "Arch Learners"],
    runsOnOldHardware: true,
    minRamGb: 2,
    recommendedRamGb: 8,
    gamingScore: 10,
    developerScore: 10,
    serverScore: 5,
    pros: [
      "Direct access to Arch repositories with 0 delay",
      "Minimal pre-installed software: your system, your choices",
      "Warmest, most helpful Linux community",
      "Welcome App with one-click mirror ranking and driver install",
    ],
    cons: ["Assumes willingness to use the terminal", "Rolling release maintenance requirements"],
    websiteUrl: "https://endeavouros.com",
    downloadUrl: "https://endeavouros.com/latest-release",
    originCountry: "Netherlands",
    firstReleaseYear: 2019,
  },
  {
    id: "nixos",
    name: "NixOS",
    tagline: "Declarative, reproducible, and unbreakable Linux",
    description:
      "NixOS is built around the Nix package manager. Your entire system configuration (packages, services, users, network) is written in a single declarative file. Every update is atomic and can be rolled back instantly.",
    logo: "❄️",
    badge: "DevOps & Reproducibility",
    base: "Independent",
    difficulty: "Advanced",
    releaseModel: "Rolling",
    defaultDesktop: "GNOME / KDE / None",
    supportedDesktops: ["GNOME", "KDE Plasma", "Hyprland", "i3", "Sway"],
    packageManager: "Nix",
    packageManagerCmd: "nix-env -iA nixos.<pkg>  or  edit configuration.nix",
    targetAudience: ["DevOps Engineers", "Developers", "System Architects", "Advanced Enthusiasts"],
    runsOnOldHardware: false,
    minRamGb: 4,
    recommendedRamGb: 16,
    gamingScore: 8,
    developerScore: 10,
    serverScore: 10,
    pros: [
      "100% reproducible environments across any machine",
      "Atomic upgrades and instant bootloader rollbacks if an update breaks",
      "Huge Nixpkgs package collection (largest repository in the world)",
      "Declarative dotfiles and system management",
    ],
    cons: [
      "Steep learning curve to learn the Nix functional language",
      "Non-FHS filesystem breaks standard binary executables without patch",
    ],
    websiteUrl: "https://nixos.org",
    downloadUrl: "https://nixos.org/download.html",
    originCountry: "Netherlands",
    firstReleaseYear: 2003,
  },
  {
    id: "kali-linux",
    name: "Kali Linux",
    tagline: "The standard for cybersecurity professionals and penetration testing",
    description:
      "Kali Linux is a Debian-derived distribution designed for digital forensics and penetration testing. It comes pre-loaded with over 600 penetration testing tools including Nmap, Wireshark, Metasploit, and Burp Suite.",
    logo: "🐉",
    badge: "Ethical Hacking & Security",
    base: "Debian",
    difficulty: "Advanced",
    releaseModel: "Rolling",
    defaultDesktop: "XFCE",
    supportedDesktops: ["XFCE", "GNOME", "KDE Plasma"],
    packageManager: "APT",
    packageManagerCmd: "sudo apt install <pkg>",
    targetAudience: ["Security Researchers", "Penetration Testers", "Forensic Analysts"],
    runsOnOldHardware: true,
    minRamGb: 2,
    recommendedRamGb: 8,
    gamingScore: 3,
    developerScore: 8,
    serverScore: 7,
    pros: [
      "600+ pre-installed security, wireless, and forensic tools",
      "Kali Undercover mode for simulating Windows in public",
      "Extensive documentation and OffSec training alignment",
      "ARM and Raspberry Pi builds available",
    ],
    cons: [
      "NOT recommended as a daily driver desktop",
      "Requires advanced Linux knowledge to use safely",
    ],
    websiteUrl: "https://kali.org",
    downloadUrl: "https://kali.org/get-kali",
    originCountry: "USA",
    firstReleaseYear: 2013,
  },
  {
    id: "rocky-linux",
    name: "Rocky Linux",
    tagline: "Enterprise Linux, 100% bug-for-bug compatible with RHEL",
    description:
      "Created by Gregory Kurtzer (founder of CentOS), Rocky Linux is designed to serve as a drop-in replacement for CentOS and Red Hat Enterprise Linux (RHEL), backed by a community charter.",
    logo: "🏔️",
    badge: "Enterprise Server",
    base: "Red Hat / Fedora",
    difficulty: "Intermediate",
    releaseModel: "Regular / LTS",
    defaultDesktop: "GNOME / Headless Server",
    supportedDesktops: ["GNOME", "Headless / CLI"],
    packageManager: "DNF / RPM",
    packageManagerCmd: "sudo dnf install <pkg>",
    targetAudience: ["Sysadmins", "Cloud Engineers", "Enterprises", "HPC Clusters"],
    runsOnOldHardware: false,
    minRamGb: 2,
    recommendedRamGb: 8,
    gamingScore: 4,
    developerScore: 9,
    serverScore: 10,
    pros: [
      "10-year enterprise lifecycle support",
      "100% compatible with Red Hat Enterprise Linux",
      "Trusted by universities, supercomputing labs, and cloud providers",
      "Production-grade SELinux and firewall defaults",
    ],
    cons: [
      "Conservative package versions not intended for desktop gaming",
      "Proprietary desktop codecs require extra repos",
    ],
    websiteUrl: "https://rockylinux.org",
    downloadUrl: "https://rockylinux.org/download",
    originCountry: "USA",
    firstReleaseYear: 2021,
  },
  {
    id: "bazzite",
    name: "Bazzite (Fedora Silverblue based)",
    tagline: "The SteamOS clone for PC, Steam Deck, and handheld gaming consoles",
    description:
      "Bazzite is an OCI container-based immutable gaming operating system built on Fedora Atomic. It includes pre-installed Steam, Lutris, Proton, GameMode, Nvidia/AMD drivers, and Steam Deck Gamepad UI mode.",
    logo: "🎮",
    badge: "Best for Steam Deck & PC Gaming",
    base: "Red Hat / Fedora",
    difficulty: "Beginner",
    releaseModel: "Immutable",
    defaultDesktop: "KDE Plasma / GNOME",
    supportedDesktops: ["KDE Plasma (Steam Deck style)", "GNOME"],
    packageManager: "Flatpak / rpm-ostree",
    packageManagerCmd: "flatpak install <pkg>  or  ujust install-<tool>",
    targetAudience: ["PC Gamers", "Steam Deck / ROG Ally / Legion Go owners", "Living Room HTPCs"],
    runsOnOldHardware: false,
    minRamGb: 8,
    recommendedRamGb: 16,
    gamingScore: 10,
    developerScore: 8,
    serverScore: 4,
    pros: [
      "Boot directly into Steam Gamepad UI mode like a console",
      "Immutable atomic OS: updates never break your system",
      "HDR, VRR, Wayland, and controller mapping out of the box",
      "Pre-configured for Steam Deck, ASUS ROG Ally, and Lenovo Legion Go",
    ],
    cons: [
      "Root filesystem is read-only; requires Flatpak for desktop software",
      "Different workflow for traditional sysadmin packages",
    ],
    websiteUrl: "https://bazzite.gg",
    downloadUrl: "https://bazzite.gg/#download",
    originCountry: "Universal Blue Project",
    firstReleaseYear: 2023,
  },
  {
    id: "tails",
    name: "Tails OS",
    tagline: "Privacy for anyone anywhere — leave no trace on your computer",
    description:
      "Tails (The Amnesic Incognito Live System) is a security-focused Debian-based Linux distribution aimed at preserving privacy and anonymity. All outgoing connections are forced through Tor, and everything runs from RAM.",
    logo: "🧅",
    badge: "Maximum Privacy",
    base: "Debian",
    difficulty: "Beginner",
    releaseModel: "Regular / LTS",
    defaultDesktop: "GNOME",
    supportedDesktops: ["GNOME"],
    packageManager: "APT (Ephemeral)",
    packageManagerCmd: "sudo apt install <pkg>",
    targetAudience: ["Journalists", "Whistleblowers", "Privacy Advocates", "Activists"],
    runsOnOldHardware: true,
    minRamGb: 2,
    recommendedRamGb: 4,
    gamingScore: 1,
    developerScore: 5,
    serverScore: 3,
    pros: [
      "Leaves zero trace on the hard drive; runs 100% from RAM Live USB",
      "All internet traffic encrypted and routed through the Tor network",
      "Built-in cryptographic tools for email, files, and chat",
      "Emergency wipe on USB unplug",
    ],
    cons: [
      "Not designed for permanent installation or everyday gaming/dev",
      "Tor speeds can be slower than direct internet",
    ],
    websiteUrl: "https://tails.net",
    downloadUrl: "https://tails.net/install",
    originCountry: "Bouvet Island / Worldwide",
    firstReleaseYear: 2009,
  },
  {
    id: "alpine-linux",
    name: "Alpine Linux",
    tagline: "Small, simple, and ultra-secure Linux for Docker containers",
    description:
      "Alpine Linux is a security-oriented, lightweight Linux distribution based on musl libc and busybox. Its base image is only 5 MB, making it the de-facto standard for containerized microservices.",
    logo: "🏔️",
    badge: "Container Favorite",
    base: "Independent",
    difficulty: "Advanced",
    releaseModel: "Regular / LTS",
    defaultDesktop: "Headless / CLI",
    supportedDesktops: ["Headless", "XFCE (Optional)"],
    packageManager: "APK",
    packageManagerCmd: "apk add <pkg>",
    targetAudience: ["DevOps", "Container Engineers", "Embedded Systems", "Minimalists"],
    runsOnOldHardware: true,
    minRamGb: 0.5,
    recommendedRamGb: 1,
    gamingScore: 1,
    developerScore: 8,
    serverScore: 9,
    pros: [
      "Base image is under 5 MB",
      "Runs entirely from RAM if configured",
      "Uses OpenRC init and musl libc for fast boot times",
      "Extremely low memory footprint",
    ],
    cons: [
      "musl libc can be incompatible with some pre-compiled glibc binaries",
      "Not designed as a mainstream desktop",
    ],
    websiteUrl: "https://alpinelinux.org",
    downloadUrl: "https://alpinelinux.org/downloads",
    originCountry: "Norway / Worldwide",
    firstReleaseYear: 2005,
  },
];
