/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CertificationRouteImport } from './routes/certification'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CheatSheetsRouteImport } from './routes/cheat-sheets'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DistroFinderRouteImport } from './routes/distro-finder'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as GamingRouteImport } from './routes/gaming'
import { Route as HardwareCompatibilityRouteImport } from './routes/hardware-compatibility'
import { Route as LabRouteImport } from './routes/lab'
import { Route as MigrationGuidesRouteImport } from './routes/migration-guides'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as DistrosIndexRouteImport } from './routes/distros.index'
import { Route as DocsCommandRouteImport } from './routes/docs.$command'
import { Route as ExamPracticeRouteImport } from './routes/exam.practice'
import { Route as ToolsCommandTranslatorRouteImport } from './routes/tools.command-translator'
import { Route as ToolsCronBuilderRouteImport } from './routes/tools.cron-builder'
import { Route as ToolsPermissionsCalculatorRouteImport } from './routes/tools.permissions-calculator'
import { Route as TutorialsIndexRouteImport } from './routes/tutorials.index'
import { Route as VerifyUuidRouteImport } from './routes/verify.$uuid'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCourseIdRouteImport } from './routes/_authenticated/admin.$courseId'
import { Route as AuthenticatedAdminManageCoursesRouteImport } from './routes/_authenticated/admin.manage-courses'
import { Route as CoursesSlugIndexRouteImport } from './routes/courses.$slug.index'
import { Route as CoursesSlugLessonRouteImport } from './routes/courses.$slug.$lesson'
import { Route as CoursesSlugPracticeRouteImport } from './routes/courses.$slug.practice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationRoute = CertificationRouteImport.update({
  id: '/certification',
  path: '/certification',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatSheetsRoute = CheatSheetsRouteImport.update({
  id: '/cheat-sheets',
  path: '/cheat-sheets',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DistroFinderRoute = DistroFinderRouteImport.update({
  id: '/distro-finder',
  path: '/distro-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const GamingRoute = GamingRouteImport.update({
  id: '/gaming',
  path: '/gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareCompatibilityRoute = HardwareCompatibilityRouteImport.update({
  id: '/hardware-compatibility',
  path: '/hardware-compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationGuidesRoute = MigrationGuidesRouteImport.update({
  id: '/migration-guides',
  path: '/migration-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const DistrosIndexRoute = DistrosIndexRouteImport.update({
  id: '/distros/',
  path: '/distros/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCommandRoute = DocsCommandRouteImport.update({
  id: '/$command',
  path: '/$command',
  getParentRoute: () => DocsRoute,
} as any)
const ExamPracticeRoute = ExamPracticeRouteImport.update({
  id: '/exam/practice',
  path: '/exam/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCommandTranslatorRoute = ToolsCommandTranslatorRouteImport.update({
  id: '/tools/command-translator',
  path: '/tools/command-translator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCronBuilderRoute = ToolsCronBuilderRouteImport.update({
  id: '/tools/cron-builder',
  path: '/tools/cron-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPermissionsCalculatorRoute =
  ToolsPermissionsCalculatorRouteImport.update({
    id: '/tools/permissions-calculator',
    path: '/tools/permissions-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TutorialsIndexRoute = TutorialsIndexRouteImport.update({
  id: '/tutorials/',
  path: '/tutorials/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyUuidRoute = VerifyUuidRouteImport.update({
  id: '/verify/$uuid',
  path: '/verify/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCourseIdRoute =
  AuthenticatedAdminCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminManageCoursesRoute =
  AuthenticatedAdminManageCoursesRouteImport.update({
    id: '/manage-courses',
    path: '/manage-courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const CoursesSlugIndexRoute = CoursesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesSlugRoute,
} as any)
const CoursesSlugLessonRoute = CoursesSlugLessonRouteImport.update({
  id: '/$lesson',
  path: '/$lesson',
  getParentRoute: () => CoursesSlugRoute,
} as any)
const CoursesSlugPracticeRoute = CoursesSlugPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => CoursesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/certification': typeof CertificationRoute
  '/chat': typeof ChatRoute
  '/cheat-sheets': typeof CheatSheetsRoute
  '/courses': typeof CoursesRouteWithChildren
  '/distro-finder': typeof DistroFinderRoute
  '/docs': typeof DocsRouteWithChildren
  '/gaming': typeof GamingRoute
  '/hardware-compatibility': typeof HardwareCompatibilityRoute
  '/lab': typeof LabRoute
  '/migration-guides': typeof MigrationGuidesRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/docs/$command': typeof DocsCommandRoute
  '/exam/practice': typeof ExamPracticeRoute
  '/tools/command-translator': typeof ToolsCommandTranslatorRoute
  '/tools/cron-builder': typeof ToolsCronBuilderRoute
  '/tools/permissions-calculator': typeof ToolsPermissionsCalculatorRoute
  '/verify/$uuid': typeof VerifyUuidRoute
  '/courses/': typeof CoursesIndexRoute
  '/distros/': typeof DistrosIndexRoute
  '/tutorials/': typeof TutorialsIndexRoute
  '/admin/$courseId': typeof AuthenticatedAdminCourseIdRoute
  '/admin/manage-courses': typeof AuthenticatedAdminManageCoursesRoute
  '/courses/$slug/$lesson': typeof CoursesSlugLessonRoute
  '/courses/$slug/practice': typeof CoursesSlugPracticeRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/certification': typeof CertificationRoute
  '/chat': typeof ChatRoute
  '/cheat-sheets': typeof CheatSheetsRoute
  '/distro-finder': typeof DistroFinderRoute
  '/docs': typeof DocsRouteWithChildren
  '/gaming': typeof GamingRoute
  '/hardware-compatibility': typeof HardwareCompatibilityRoute
  '/lab': typeof LabRoute
  '/migration-guides': typeof MigrationGuidesRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/docs/$command': typeof DocsCommandRoute
  '/exam/practice': typeof ExamPracticeRoute
  '/tools/command-translator': typeof ToolsCommandTranslatorRoute
  '/tools/cron-builder': typeof ToolsCronBuilderRoute
  '/tools/permissions-calculator': typeof ToolsPermissionsCalculatorRoute
  '/verify/$uuid': typeof VerifyUuidRoute
  '/courses': typeof CoursesIndexRoute
  '/distros': typeof DistrosIndexRoute
  '/tutorials': typeof TutorialsIndexRoute
  '/admin/$courseId': typeof AuthenticatedAdminCourseIdRoute
  '/admin/manage-courses': typeof AuthenticatedAdminManageCoursesRoute
  '/courses/$slug/$lesson': typeof CoursesSlugLessonRoute
  '/courses/$slug/practice': typeof CoursesSlugPracticeRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/courses/$slug': typeof CoursesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/certification': typeof CertificationRoute
  '/chat': typeof ChatRoute
  '/cheat-sheets': typeof CheatSheetsRoute
  '/courses': typeof CoursesRouteWithChildren
  '/distro-finder': typeof DistroFinderRoute
  '/docs': typeof DocsRouteWithChildren
  '/gaming': typeof GamingRoute
  '/hardware-compatibility': typeof HardwareCompatibilityRoute
  '/lab': typeof LabRoute
  '/migration-guides': typeof MigrationGuidesRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/docs/$command': typeof DocsCommandRoute
  '/exam/practice': typeof ExamPracticeRoute
  '/tools/command-translator': typeof ToolsCommandTranslatorRoute
  '/tools/cron-builder': typeof ToolsCronBuilderRoute
  '/tools/permissions-calculator': typeof ToolsPermissionsCalculatorRoute
  '/verify/$uuid': typeof VerifyUuidRoute
  '/courses/': typeof CoursesIndexRoute
  '/distros/': typeof DistrosIndexRoute
  '/tutorials/': typeof TutorialsIndexRoute
  '/_authenticated/admin/$courseId': typeof AuthenticatedAdminCourseIdRoute
  '/_authenticated/admin/manage-courses': typeof AuthenticatedAdminManageCoursesRoute
  '/courses/$slug/$lesson': typeof CoursesSlugLessonRoute
  '/courses/$slug/practice': typeof CoursesSlugPracticeRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/auth'
    | '/certification'
    | '/chat'
    | '/cheat-sheets'
    | '/courses'
    | '/distro-finder'
    | '/docs'
    | '/gaming'
    | '/hardware-compatibility'
    | '/lab'
    | '/migration-guides'
    | '/resources'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/courses/$slug'
    | '/docs/$command'
    | '/exam/practice'
    | '/tools/command-translator'
    | '/tools/cron-builder'
    | '/tools/permissions-calculator'
    | '/verify/$uuid'
    | '/courses/'
    | '/distros/'
    | '/tutorials/'
    | '/admin/$courseId'
    | '/admin/manage-courses'
    | '/courses/$slug/$lesson'
    | '/courses/$slug/practice'
    | '/admin/'
    | '/courses/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/auth'
    | '/certification'
    | '/chat'
    | '/cheat-sheets'
    | '/distro-finder'
    | '/docs'
    | '/gaming'
    | '/hardware-compatibility'
    | '/lab'
    | '/migration-guides'
    | '/resources'
    | '/terms'
    | '/dashboard'
    | '/profile'
    | '/docs/$command'
    | '/exam/practice'
    | '/tools/command-translator'
    | '/tools/cron-builder'
    | '/tools/permissions-calculator'
    | '/verify/$uuid'
    | '/courses'
    | '/distros'
    | '/tutorials'
    | '/admin/$courseId'
    | '/admin/manage-courses'
    | '/courses/$slug/$lesson'
    | '/courses/$slug/practice'
    | '/admin'
    | '/courses/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apps'
    | '/auth'
    | '/certification'
    | '/chat'
    | '/cheat-sheets'
    | '/courses'
    | '/distro-finder'
    | '/docs'
    | '/gaming'
    | '/hardware-compatibility'
    | '/lab'
    | '/migration-guides'
    | '/resources'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/courses/$slug'
    | '/docs/$command'
    | '/exam/practice'
    | '/tools/command-translator'
    | '/tools/cron-builder'
    | '/tools/permissions-calculator'
    | '/verify/$uuid'
    | '/courses/'
    | '/distros/'
    | '/tutorials/'
    | '/_authenticated/admin/$courseId'
    | '/_authenticated/admin/manage-courses'
    | '/courses/$slug/$lesson'
    | '/courses/$slug/practice'
    | '/_authenticated/admin/'
    | '/courses/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppsRoute: typeof AppsRoute
  AuthRoute: typeof AuthRoute
  CertificationRoute: typeof CertificationRoute
  ChatRoute: typeof ChatRoute
  CheatSheetsRoute: typeof CheatSheetsRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DistroFinderRoute: typeof DistroFinderRoute
  DocsRoute: typeof DocsRouteWithChildren
  GamingRoute: typeof GamingRoute
  HardwareCompatibilityRoute: typeof HardwareCompatibilityRoute
  LabRoute: typeof LabRoute
  MigrationGuidesRoute: typeof MigrationGuidesRoute
  ResourcesRoute: typeof ResourcesRoute
  TermsRoute: typeof TermsRoute
  ExamPracticeRoute: typeof ExamPracticeRoute
  ToolsCommandTranslatorRoute: typeof ToolsCommandTranslatorRoute
  ToolsCronBuilderRoute: typeof ToolsCronBuilderRoute
  ToolsPermissionsCalculatorRoute: typeof ToolsPermissionsCalculatorRoute
  VerifyUuidRoute: typeof VerifyUuidRoute
  DistrosIndexRoute: typeof DistrosIndexRoute
  TutorialsIndexRoute: typeof TutorialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification': {
      id: '/certification'
      path: '/certification'
      fullPath: '/certification'
      preLoaderRoute: typeof CertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheat-sheets': {
      id: '/cheat-sheets'
      path: '/cheat-sheets'
      fullPath: '/cheat-sheets'
      preLoaderRoute: typeof CheatSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distro-finder': {
      id: '/distro-finder'
      path: '/distro-finder'
      fullPath: '/distro-finder'
      preLoaderRoute: typeof DistroFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaming': {
      id: '/gaming'
      path: '/gaming'
      fullPath: '/gaming'
      preLoaderRoute: typeof GamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware-compatibility': {
      id: '/hardware-compatibility'
      path: '/hardware-compatibility'
      fullPath: '/hardware-compatibility'
      preLoaderRoute: typeof HardwareCompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration-guides': {
      id: '/migration-guides'
      path: '/migration-guides'
      fullPath: '/migration-guides'
      preLoaderRoute: typeof MigrationGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/distros/': {
      id: '/distros/'
      path: '/distros'
      fullPath: '/distros/'
      preLoaderRoute: typeof DistrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$command': {
      id: '/docs/$command'
      path: '/$command'
      fullPath: '/docs/$command'
      preLoaderRoute: typeof DocsCommandRouteImport
      parentRoute: typeof DocsRoute
    }
    '/exam/practice': {
      id: '/exam/practice'
      path: '/exam/practice'
      fullPath: '/exam/practice'
      preLoaderRoute: typeof ExamPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/command-translator': {
      id: '/tools/command-translator'
      path: '/tools/command-translator'
      fullPath: '/tools/command-translator'
      preLoaderRoute: typeof ToolsCommandTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cron-builder': {
      id: '/tools/cron-builder'
      path: '/tools/cron-builder'
      fullPath: '/tools/cron-builder'
      preLoaderRoute: typeof ToolsCronBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/permissions-calculator': {
      id: '/tools/permissions-calculator'
      path: '/tools/permissions-calculator'
      fullPath: '/tools/permissions-calculator'
      preLoaderRoute: typeof ToolsPermissionsCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials/': {
      id: '/tutorials/'
      path: '/tutorials'
      fullPath: '/tutorials/'
      preLoaderRoute: typeof TutorialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$uuid': {
      id: '/verify/$uuid'
      path: '/verify/$uuid'
      fullPath: '/verify/$uuid'
      preLoaderRoute: typeof VerifyUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$courseId': {
      id: '/_authenticated/admin/$courseId'
      path: '/$courseId'
      fullPath: '/admin/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/manage-courses': {
      id: '/_authenticated/admin/manage-courses'
      path: '/manage-courses'
      fullPath: '/admin/manage-courses'
      preLoaderRoute: typeof AuthenticatedAdminManageCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/courses/$slug/': {
      id: '/courses/$slug/'
      path: '/'
      fullPath: '/courses/$slug/'
      preLoaderRoute: typeof CoursesSlugIndexRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
    '/courses/$slug/$lesson': {
      id: '/courses/$slug/$lesson'
      path: '/$lesson'
      fullPath: '/courses/$slug/$lesson'
      preLoaderRoute: typeof CoursesSlugLessonRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
    '/courses/$slug/practice': {
      id: '/courses/$slug/practice'
      path: '/practice'
      fullPath: '/courses/$slug/practice'
      preLoaderRoute: typeof CoursesSlugPracticeRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCourseIdRoute: typeof AuthenticatedAdminCourseIdRoute
  AuthenticatedAdminManageCoursesRoute: typeof AuthenticatedAdminManageCoursesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCourseIdRoute: AuthenticatedAdminCourseIdRoute,
  AuthenticatedAdminManageCoursesRoute: AuthenticatedAdminManageCoursesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CoursesSlugRouteChildren {
  CoursesSlugLessonRoute: typeof CoursesSlugLessonRoute
  CoursesSlugPracticeRoute: typeof CoursesSlugPracticeRoute
  CoursesSlugIndexRoute: typeof CoursesSlugIndexRoute
}

const CoursesSlugRouteChildren: CoursesSlugRouteChildren = {
  CoursesSlugLessonRoute: CoursesSlugLessonRoute,
  CoursesSlugPracticeRoute: CoursesSlugPracticeRoute,
  CoursesSlugIndexRoute: CoursesSlugIndexRoute,
}

const CoursesSlugRouteWithChildren = CoursesSlugRoute._addFileChildren(
  CoursesSlugRouteChildren,
)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRouteWithChildren
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRouteWithChildren,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface DocsRouteChildren {
  DocsCommandRoute: typeof DocsCommandRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCommandRoute: DocsCommandRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppsRoute: AppsRoute,
  AuthRoute: AuthRoute,
  CertificationRoute: CertificationRoute,
  ChatRoute: ChatRoute,
  CheatSheetsRoute: CheatSheetsRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DistroFinderRoute: DistroFinderRoute,
  DocsRoute: DocsRouteWithChildren,
  GamingRoute: GamingRoute,
  HardwareCompatibilityRoute: HardwareCompatibilityRoute,
  LabRoute: LabRoute,
  MigrationGuidesRoute: MigrationGuidesRoute,
  ResourcesRoute: ResourcesRoute,
  TermsRoute: TermsRoute,
  ExamPracticeRoute: ExamPracticeRoute,
  ToolsCommandTranslatorRoute: ToolsCommandTranslatorRoute,
  ToolsCronBuilderRoute: ToolsCronBuilderRoute,
  ToolsPermissionsCalculatorRoute: ToolsPermissionsCalculatorRoute,
  VerifyUuidRoute: VerifyUuidRoute,
  DistrosIndexRoute: DistrosIndexRoute,
  TutorialsIndexRoute: TutorialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
