/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LabRouteImport } from './routes/lab'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as DocsCommandRouteImport } from './routes/docs.$command'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCourseIdRouteImport } from './routes/_authenticated/admin.$courseId'
import { Route as AuthenticatedAdminManageCoursesRouteImport } from './routes/_authenticated/admin.manage-courses'
import { Route as CoursesSlugIndexRouteImport } from './routes/courses.$slug.index'
import { Route as CoursesSlugLessonRouteImport } from './routes/courses.$slug.$lesson'
import { Route as CoursesSlugPracticeRouteImport } from './routes/courses.$slug.practice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const DocsCommandRoute = DocsCommandRouteImport.update({
  id: '/$command',
  path: '/$command',
  getParentRoute: () => DocsRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCourseIdRoute =
  AuthenticatedAdminCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminManageCoursesRoute =
  AuthenticatedAdminManageCoursesRouteImport.update({
    id: '/manage-courses',
    path: '/manage-courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const CoursesSlugIndexRoute = CoursesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesSlugRoute,
} as any)
const CoursesSlugLessonRoute = CoursesSlugLessonRouteImport.update({
  id: '/$lesson',
  path: '/$lesson',
  getParentRoute: () => CoursesSlugRoute,
} as any)
const CoursesSlugPracticeRoute = CoursesSlugPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => CoursesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/courses': typeof CoursesRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/lab': typeof LabRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/docs/$command': typeof DocsCommandRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/$courseId': typeof AuthenticatedAdminCourseIdRoute
  '/admin/manage-courses': typeof AuthenticatedAdminManageCoursesRoute
  '/courses/$slug/$lesson': typeof CoursesSlugLessonRoute
  '/courses/$slug/practice': typeof CoursesSlugPracticeRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/docs': typeof DocsRouteWithChildren
  '/lab': typeof LabRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/docs/$command': typeof DocsCommandRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/$courseId': typeof AuthenticatedAdminCourseIdRoute
  '/admin/manage-courses': typeof AuthenticatedAdminManageCoursesRoute
  '/courses/$slug/$lesson': typeof CoursesSlugLessonRoute
  '/courses/$slug/practice': typeof CoursesSlugPracticeRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/courses/$slug': typeof CoursesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/courses': typeof CoursesRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/lab': typeof LabRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/docs/$command': typeof DocsCommandRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/admin/$courseId': typeof AuthenticatedAdminCourseIdRoute
  '/_authenticated/admin/manage-courses': typeof AuthenticatedAdminManageCoursesRoute
  '/courses/$slug/$lesson': typeof CoursesSlugLessonRoute
  '/courses/$slug/practice': typeof CoursesSlugPracticeRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/courses'
    | '/docs'
    | '/lab'
    | '/resources'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/courses/$slug'
    | '/docs/$command'
    | '/courses/'
    | '/admin/$courseId'
    | '/admin/manage-courses'
    | '/courses/$slug/$lesson'
    | '/courses/$slug/practice'
    | '/admin/'
    | '/courses/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/docs'
    | '/lab'
    | '/resources'
    | '/terms'
    | '/dashboard'
    | '/profile'
    | '/docs/$command'
    | '/courses'
    | '/admin/$courseId'
    | '/admin/manage-courses'
    | '/courses/$slug/$lesson'
    | '/courses/$slug/practice'
    | '/admin'
    | '/courses/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/chat'
    | '/courses'
    | '/docs'
    | '/lab'
    | '/resources'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/courses/$slug'
    | '/docs/$command'
    | '/courses/'
    | '/_authenticated/admin/$courseId'
    | '/_authenticated/admin/manage-courses'
    | '/courses/$slug/$lesson'
    | '/courses/$slug/practice'
    | '/_authenticated/admin/'
    | '/courses/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  LabRoute: typeof LabRoute
  ResourcesRoute: typeof ResourcesRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/docs/$command': {
      id: '/docs/$command'
      path: '/$command'
      fullPath: '/docs/$command'
      preLoaderRoute: typeof DocsCommandRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$courseId': {
      id: '/_authenticated/admin/$courseId'
      path: '/$courseId'
      fullPath: '/admin/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/manage-courses': {
      id: '/_authenticated/admin/manage-courses'
      path: '/manage-courses'
      fullPath: '/admin/manage-courses'
      preLoaderRoute: typeof AuthenticatedAdminManageCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/courses/$slug/': {
      id: '/courses/$slug/'
      path: '/'
      fullPath: '/courses/$slug/'
      preLoaderRoute: typeof CoursesSlugIndexRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
    '/courses/$slug/$lesson': {
      id: '/courses/$slug/$lesson'
      path: '/$lesson'
      fullPath: '/courses/$slug/$lesson'
      preLoaderRoute: typeof CoursesSlugLessonRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
    '/courses/$slug/practice': {
      id: '/courses/$slug/practice'
      path: '/practice'
      fullPath: '/courses/$slug/practice'
      preLoaderRoute: typeof CoursesSlugPracticeRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCourseIdRoute: typeof AuthenticatedAdminCourseIdRoute
  AuthenticatedAdminManageCoursesRoute: typeof AuthenticatedAdminManageCoursesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCourseIdRoute: AuthenticatedAdminCourseIdRoute,
  AuthenticatedAdminManageCoursesRoute: AuthenticatedAdminManageCoursesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CoursesSlugRouteChildren {
  CoursesSlugLessonRoute: typeof CoursesSlugLessonRoute
  CoursesSlugPracticeRoute: typeof CoursesSlugPracticeRoute
  CoursesSlugIndexRoute: typeof CoursesSlugIndexRoute
}

const CoursesSlugRouteChildren: CoursesSlugRouteChildren = {
  CoursesSlugLessonRoute: CoursesSlugLessonRoute,
  CoursesSlugPracticeRoute: CoursesSlugPracticeRoute,
  CoursesSlugIndexRoute: CoursesSlugIndexRoute,
}

const CoursesSlugRouteWithChildren = CoursesSlugRoute._addFileChildren(
  CoursesSlugRouteChildren,
)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRouteWithChildren
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRouteWithChildren,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface DocsRouteChildren {
  DocsCommandRoute: typeof DocsCommandRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCommandRoute: DocsCommandRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  LabRoute: LabRoute,
  ResourcesRoute: ResourcesRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
